[package]
name = "colombiniSAT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dimacs = "0.2.0"
sat = "0.1.0"
